Traceback (most recent call last):
  File "c:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df=pd.read_clipboard()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStopIteration[0m                             Traceback (most recent call last)
[1;32mc:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\pandas\io\parsers\python_parser.py[0m in [0;36m_infer_columns[1;34m(self)[0m
[0;32m    375[0m                 [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 376[1;33m                     [0mline[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_buffered_line[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    377[0m [1;33m[0m[0m

[1;32mc:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\pandas\io\parsers\python_parser.py[0m in [0;36m_buffered_line[1;34m(self)[0m
[0;32m    583[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 584[1;33m             [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_next_line[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    585[0m [1;33m[0m[0m

[1;32mc:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\pandas\io\parsers\python_parser.py[0m in [0;36m_next_line[1;34m(self)[0m
[0;32m    680[0m             [1;32mwhile[0m [1;32mTrue[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 681[1;33m                 [0morig_line[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_next_iter_line[0m[1;33m([0m[0mrow_num[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0mpos[0m [1;33m+[0m [1;36m1[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    682[0m                 [0mself[0m[1;33m.[0m[0mpos[0m [1;33m+=[0m [1;36m1[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\pandas\io\parsers\python_parser.py[0m in [0;36m_next_iter_line[1;34m(self, row_num)[0m
[0;32m    741[0m             [1;32massert[0m [0mself[0m[1;33m.[0m[0mdata[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 742[1;33m             [1;32mreturn[0m [0mnext[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mdata[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    743[0m         [1;32mexcept[0m [0mcsv[0m[1;33m.[0m[0mError[0m [1;32mas[0m [0me[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mStopIteration[0m: 

The above exception was the direct cause of the following exception:

[1;31mEmptyDataError[0m                            Traceback (most recent call last)
[1;32m<ipython-input-3-8aa785b0b4bd>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mdf[0m[1;33m=[0m[0mpd[0m[1;33m.[0m[0mread_clipboard[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32mc:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\pandas\io\clipboards.py[0m in [0;36mread_clipboard[1;34m(sep, **kwargs)[0m
[0;32m     81[0m         )
[0;32m     82[0m [1;33m[0m[0m
[1;32m---> 83[1;33m     [1;32mreturn[0m [0mread_csv[0m[1;33m([0m[0mStringIO[0m[1;33m([0m[0mtext[0m[1;33m)[0m[1;33m,[0m [0msep[0m[1;33m=[0m[0msep[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     84[0m [1;33m[0m[0m
[0;32m     85[0m [1;33m[0m[0m

[1;32mc:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\pandas\util\_decorators.py[0m in [0;36mwrapper[1;34m(*args, **kwargs)[0m
[0;32m    309[0m                     [0mstacklevel[0m[1;33m=[0m[0mstacklevel[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    310[0m                 )
[1;32m--> 311[1;33m             [1;32mreturn[0m [0mfunc[0m[1;33m([0m[1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    312[0m [1;33m[0m[0m
[0;32m    313[0m         [1;32mreturn[0m [0mwrapper[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36mread_csv[1;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)[0m
[0;32m    584[0m     [0mkwds[0m[1;33m.[0m[0mupdate[0m[1;33m([0m[0mkwds_defaults[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    585[0m [1;33m[0m[0m
[1;32m--> 586[1;33m     [1;32mreturn[0m [0m_read[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    587[0m [1;33m[0m[0m
[0;32m    588[0m [1;33m[0m[0m

[1;32mc:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m_read[1;34m(filepath_or_buffer, kwds)[0m
[0;32m    480[0m [1;33m[0m[0m
[0;32m    481[0m     [1;31m# Create the parser.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 482[1;33m     [0mparser[0m [1;33m=[0m [0mTextFileReader[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    483[0m [1;33m[0m[0m
[0;32m    484[0m     [1;32mif[0m [0mchunksize[0m [1;32mor[0m [0miterator[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m__init__[1;34m(self, f, engine, **kwds)[0m
[0;32m    809[0m             [0mself[0m[1;33m.[0m[0moptions[0m[1;33m[[0m[1;34m"has_index_names"[0m[1;33m][0m [1;33m=[0m [0mkwds[0m[1;33m[[0m[1;34m"has_index_names"[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m    810[0m [1;33m[0m[0m
[1;32m--> 811[1;33m         [0mself[0m[1;33m.[0m[0m_engine[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_make_engine[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mengine[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    812[0m [1;33m[0m[0m
[0;32m    813[0m     [1;32mdef[0m [0mclose[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\pandas\io\parsers\readers.py[0m in [0;36m_make_engine[1;34m(self, engine)[0m
[0;32m   1038[0m             )
[0;32m   1039[0m         [1;31m# error: Too many arguments for "ParserBase"[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1040[1;33m         [1;32mreturn[0m [0mmapping[0m[1;33m[[0m[0mengine[0m[1;33m][0m[1;33m([0m[0mself[0m[1;33m.[0m[0mf[0m[1;33m,[0m [1;33m**[0m[0mself[0m[1;33m.[0m[0moptions[0m[1;33m)[0m  [1;31m# type: ignore[call-arg][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1041[0m [1;33m[0m[0m
[0;32m   1042[0m     [1;32mdef[0m [0m_failover_to_python[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\pandas\io\parsers\python_parser.py[0m in [0;36m__init__[1;34m(self, f, **kwds)[0m
[0;32m    111[0m                 [0mself[0m[1;33m.[0m[0mnum_original_columns[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    112[0m                 [0mself[0m[1;33m.[0m[0munnamed_cols[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 113[1;33m             ) = self._infer_columns()
[0m[0;32m    114[0m         [1;32mexcept[0m [1;33m([0m[0mTypeError[0m[1;33m,[0m [0mValueError[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    115[0m             [0mself[0m[1;33m.[0m[0mclose[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\sahil choudhary\appdata\local\programs\python\python37-32\lib\site-packages\pandas\io\parsers\python_parser.py[0m in [0;36m_infer_columns[1;34m(self)[0m
[0;32m    396[0m [1;33m[0m[0m
[0;32m    397[0m                     [1;32mif[0m [1;32mnot[0m [0mself[0m[1;33m.[0m[0mnames[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 398[1;33m                         [1;32mraise[0m [0mEmptyDataError[0m[1;33m([0m[1;34m"No columns to parse from file"[0m[1;33m)[0m [1;32mfrom[0m [0merr[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    399[0m [1;33m[0m[0m
[0;32m    400[0m                     [0mline[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mnames[0m[1;33m[[0m[1;33m:[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m

[1;31mEmptyDataError[0m: No columns to parse from file
EmptyDataError: No columns to parse from file

